name: Run Nifty Order Block Bot

on:
  schedule:
    - cron: '45 3 * * 1-5'  # 9:15 AM IST = 3:45 AM UTC (Mon-Fri)
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: ▶️ Run NIFTY Order Block Bot
        run: |
          python bot/accuracyOrderBlock.py
